---
label: CommonPost
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  config:
    required: true
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
  config:
    required: true
- type: file
  label: image
  name: image
  default: ''
- type: text
  name: comments
  label: comments
  description: comments
  config:
    required: true
  hidden: false
  default: 'true'
- type: tag_list
  name: tags
  label: tags
  description: tags
  default:
  - devops
  - architecture
  - cloud
  - development
  - best practices
  - containers
  - GCP
  - azure
  - aws
  - CloudOps
pages:
- content/post/tutorial-infraestructura-como-c贸digo-con-terraform.md
- content/post/mis-consejos-para-obtener-la-certificaci贸n-de-professional-cloud-architect-de-google-cloud.md
- content/post/microsoft-compra-citus-data-para-mejorar-la-experiencia-en-postgresql-en-azure.md
- content/post/comparaci贸n-de-bases-de-datos-en-google-cloud-datastore-vs-bigtable-vs-cloud-sql-vs-spanner-vs-bigquery.md
- content/post/simplificando-la-gesti贸n-multicloud-con-mist-io.md
